FROM nvcr.io/nvidia/dgl:23.09-py3
#FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

RUN apt-get update && apt-get install -y openssh-server

RUN mkdir /var/run/sshd
RUN echo 'root:dgl_pwd' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo "Port 2222" >> /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN mkdir /root/.ssh
RUN ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
RUN cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys

RUN pip3 install ogb
EXPOSE 22
EXPOSE 2222
CMD ["/usr/sbin/sshd", "-D", "-o", "ListenAddress=0.0.0.0"]
#CMD ["/usr/sbin/sshd", "-D"]