#FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu20.04

# Set timezone
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && echo "Europe/Berlin" > /etc/timezone

# Update and install necessary packages
RUN apt update && apt install -y software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt update \
    && apt install -y python3 python3-pip python3.10 python3.10-venv python3.10-dev python3.10-distutils \
    && apt remove -y python3-pip \
    && python3.10 -m ensurepip --default-pip \
    && python3.10 -m pip install --upgrade pip \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 \
    && update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/python3.10 1

# Install PyTorch and DGL
#RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 \
 #   && pip install dgl==1.0.1+cu117 -f https://data.dgl.ai/wheels/cu117/repo.html

# Set default python and pip versions
RUN update-alternatives --config python3 --skip-auto


RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:dgl_pwd' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo "Port 2222" >> /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd


ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN mkdir /root/.ssh
COPY id_ed25519.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN chown root:root /root/.ssh/authorized_keys
EXPOSE 22
EXPOSE 2222

CMD ["/usr/sbin/sshd", "-D", "-o", "ListenAddress=0.0.0.0"]